version: "3"
services:
  backend_main:
    build: ./main
    container_name: backend_main
    restart: unless-stopped
    expose:
      - "5000"
    env_file:
      - ./main/.env
  user:
    build: ./user
    container_name: user
    restart: unless-stopped
    expose:
      - "5001"
    env_file:
      - ./user/.env
  category:
    build: ./category
    container_name: category
    restart: unless-stopped
    expose:
      - "5002"
    env_file:
      - ./category/.env
  upload:
    build: ./upload
    container_name: upload
    restart: unless-stopped
    expose:
      - "5003"
    env_file:
      - ./upload/.env
  product:
    build: ./product
    container_name: product
    restart: unless-stopped
    expose:
      - "5004"
    env_file:
      - ./product/.env
  renting:
    build: ./renting
    container_name: renting
    restart: unless-stopped
    expose:
      - "5005"
    env_file:
      - ./renting/.env
  chat:
    build: ./chat
    container_name: chat
    restart: unless-stopped
    expose:
      - "5006"
    env_file:
      - ./chat/.env
  payment:
    build: ./payment
    container_name: payment
    restart: unless-stopped
    expose:
      - "5007"
    env_file:
      - ./payment/.env
  social:
    build: ./social
    container_name: social
    restart: unless-stopped
    expose:
      - "5009"
    env_file:
      - ./social/.env
  cancellation:
    build: ./cancellation
    container_name: cancellation
    restart: unless-stopped
    expose:
      - "5008"
    env_file:
      - ./cancellation/.env
  caddy_backend:
    image: caddy:2
    container_name: caddy_service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
